# Generated by Django 3.0.3 on 2020-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority_order',
            field=models.IntegerField(default=0),
        ),
    ]
