# Generated by Django 3.0.3 on 2020-02-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_priority_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
