# Generated by Django 3.0.3 on 2020-02-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='state',
            field=models.CharField(choices=[('inbox', 'Inbox'), ('next', 'Next'), ('waiting', 'Waiting'), ('someday', 'Someday')], default='inbox', max_length=7),
        ),
    ]
